/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : Screen Capture
 #	author : miyako
 #	2013/12/14
 #
 # --------------------------------------------------------------------------------*/

#include "4DPluginAPI.h"

// --- Windows
void CAPTURE_Window(sLONG_PTR *pResult, PackagePtr pParams);

#if VERSIONWIN
int _captureWindow(HWND	windowRef, int w, int h, C_PICTURE &picture);
int _captureWindow(HBITMAP hbmWindow, HDC hdcWindow, int w, int h, C_PICTURE &picture);
#endif