/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : screen-capture
 #	author : miyako
 #	2017/03/14
 #
 # --------------------------------------------------------------------------------*/



// --- Capture
void Capture_screen(PA_PluginParameters params);
void Capture_window(PA_PluginParameters params);
