/* --------------------------------------------------------------------------------
 #
 #	4DPlugin.h
 #	source generated by 4D Plugin Wizard
 #	Project : screen-capture
 #	author : miyako
 #	2017/03/14
 #
 # --------------------------------------------------------------------------------*/



// --- Capture
void Capture_screen(sLONG_PTR *pResult, PackagePtr pParams);
void Capture_window(sLONG_PTR *pResult, PackagePtr pParams);
